### ISSUE TITLE
NameMap - Unable to decipher

### ISSUE THREAD

**Issue by Avarik** [kotiq/wt-tools#13]
I noticed that the NameMap (nm) file is undecipherable with the current version of WT Tools, or any for that matter.
That file contains the structural use of same game code and commands, specifically for the mission editor and unit overwrite configs.

Is there any way to unlock this file or make it readable?
![image](https://user-images.githubusercontent.com/61098126/198389675-2463db01-3c01-4d14-85b1-f73b574e6471.png)

**Comment by kotiq** [comment]
The name map contains section keys and strings. You can use one of the `blk` package functions.
```python
In [1]: from blk.binary import compose_partial_names

In [2]: with open('aces.vromfs.bin_u/nm', 'rb') as fh:
   ...:     names = compose_partial_names(fh)
   ...: 

In [3]: len(names)
Out[3]: 106500

In [4]: print('\n'.join(map(lambda s: repr(str(s)), names[:5])))
'__allowedConfigOverrides'
'graphicsQuality'
'renderer'
'region'
'releaseChannel'
```
