### ISSUE TITLE
Unknown file format

### ISSUE THREAD

**Issue by Keller18306** [kotiq/wt-tools#15]
Как я понял автор говорит на русском, поэтому issue тоже уже напишу на русском.

При выполнении:
```bash
python blk_unpack_ng.py work\replays.blk
```
выдаёт:
```
work\replays.blk
    Unknown file format
```

Этот файл я взял из игры `Replays\replays.wdb`

Его копия: [replays.zip](https://github.com/kotiq/wt-tools/files/9913812/replays.zip)

Почему я вдруг решил wdb переименовать в blk? 
На вики странице написано, что это файл blk: https://github.com/klensy/wt-tools/wiki
![image](https://user-images.githubusercontent.com/23178771/199336029-e248a3ac-fa3a-4eff-ae64-6c1b0a061955.png)

Да и по содержимому он похож на один из этих, которые находятся тут: https://github.com/kotiq/blk/tree/master/tests/samples

![image](https://user-images.githubusercontent.com/23178771/199336194-7238a38c-c97d-45e5-84f0-8189fb566a97.png)

**Comment by kotiq** [comment]
В wt-tools связаны вместе работа распаковщика vromfs.bin и распаковщика blk, которые он порождает. Часть кода унаследована, и я не стал его переделывать. 
Эти файлы нового формата я назову частичными. Они не содержат заголовков (в данном случае, первый байт), которые указывают на способ распаковки. Частичные файлы не встречаются в "дикой природе": в дампах памяти, в поддиректориях игры и т.д.
Распаковщик полных файлов, как они представлены в vromfs образе, есть в dev ветке проекта blk.
```sh
python -m blk.demo.blk_unpacker replays.wdb --loglevel=debug
1667481654.872113 INFO Начало распаковки.
1667481654.900154 DEBUG '/media/games/kotiq/linux/WarThunder/Replays/replays.wdb': FAT => JSON
1667481654.900506 INFO [ OK ] '/media/games/kotiq/linux/WarThunder/Replays/replays.wdb'
1667481654.900547 INFO Успешно распаковано: 1/1
```
```sh
file replays.*
replays.wdb:  data
replays.wdbx: JSON text data
```

**Comment by Keller18306** [comment]
Я нашёл описание формата у вас в репозитории. Поэтому я уже сделал под свой язык и оно работает. Фактически моя проблема решена)
